let DEBUG_MODE,ValidationError,CustomErrorHandler;_311‍.x([["default",()=>_311‍.o]]);_311‍.w("../config",[["DEBUG_MODE",["DEBUG_MODE"],function(v){DEBUG_MODE=v}]]);_311‍.w("joi",[["ValidationError",["ValidationError"],function(v){ValidationError=v}]]);_311‍.w("../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);



const errorHandler = (err, req, res, next) => {
    let statusCode = 500;
    _311‍.g.console.log(DEBUG_MODE);
    let data = {
        message: 'Internal server error here',
        ...(DEBUG_MODE === 'true' && { originalError: err.message })
    } 

    if (err instanceof ValidationError) {
        statusCode = 422;
        data = {
            message: err.message
        }
    }

    if (err instanceof CustomErrorHandler) {
        statusCode = err.status;
        data = {
            message: err.message
        }
    }

    return res.status(statusCode).json(data);
}

_311‍.d(errorHandler);